apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-app
  namespace: obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-app
  template:
    metadata:
      labels:
        app: obs-app
    spec:
      containers:
        - name: obs-app
          image: manjvija/obs-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: obs-app
  namespace: obs
spec:
  selector:
    app: obs-app
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
